### ISSUE TITLE
Investigation: Errors when importing Rock The Vote posts.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/chompy#51]
## _BUG_

Jen has seen some _suspicious_ behavior when uploading the past few Rock The Vote CSVs. We want to track down the source of the error and make sure that everything is safely making it in to our backend.

**Comment by DFurnes** [comment]
We've had 10 failed runs of the `ImportRockTheVotePosts` job, likely from multiple attempts on a few CSVs. Here's the list of failed jobs:

```
Running php artisan queue:failed on ⬢ dosomething-chompy... up, run.9459 (Standard-1X)
+----+------------+----------+------------------------------------+---------------------+
| ID | Connection | Queue    | Class                              | Failed At           |
+----+------------+----------+------------------------------------+---------------------+
| 91 | redis      | importer | Chompy\Jobs\ImportRockTheVotePosts | 2018-10-09 16:07:21 |
| 81 | redis      | importer | Chompy\Jobs\ImportRockTheVotePosts | 2018-10-09 15:37:27 |
| 71 | redis      | importer | Chompy\Jobs\ImportRockTheVotePosts | 2018-10-09 15:11:46 |
| 61 | redis      | importer | Chompy\Jobs\ImportRockTheVotePosts | 2018-10-09 14:40:58 |
| 51 | redis      | importer | Chompy\Jobs\ImportRockTheVotePosts | 2018-10-05 21:02:03 |
| 41 | redis      | importer | Chompy\Jobs\ImportRockTheVotePosts | 2018-10-05 20:41:27 |
| 31 | redis      | importer | Chompy\Jobs\ImportRockTheVotePosts | 2018-10-05 20:16:00 |
| 21 | redis      | importer | Chompy\Jobs\ImportRockTheVotePosts | 2018-10-05 18:19:17 |
| 11 | redis      | importer | Chompy\Jobs\ImportRockTheVotePosts | 2018-10-05 18:10:51 |
| 1  | redis      | importer | Chompy\Jobs\ImportRockTheVotePosts | 2018-10-05 17:38:06 |
+----+------------+----------+------------------------------------+---------------------+
```

**Comment by DFurnes** [comment]
All of the jobs failed with the same issue, encoding a row for the `CreateRockTheVotePostInRogue` job:

```
Illuminate\Queue\InvalidPayloadException: Unable to JSON encode payload. Error code: 5 in /app/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:83
Stack trace:
...
#6 /app/app/Jobs/ImportRockTheVotePosts.php(68): Chompy\Jobs\CreateRockTheVotePostInRogue::dispatch(Array)
#7 [internal function]: Chompy\Jobs\ImportRockTheVotePosts->handle(Object(Chompy\Services\Rogue))
```

This one is from `rock-the-vote-importer2018-10-09 15:37:20.csv`.

**Comment by DFurnes** [comment]
Another interesting thing is that we have some failed _rows_, like [this one](https://papertrailapp.com/systems/dosomething-chompy/events?focus=986341900158767112&selected=986341900158767112), which logged "There was an error with that user" and what looks like a validation error but _did not_ fail the job (so we can't retry).

**Comment by DFurnes** [comment]
@katiecrane I think that's a good idea! We were trying to sleuth how far it might have gotten by looking at created user accounts, but more logging will definitely be useful here (maybe catching this `InvalidPayloadException` exception and logging the actual contents of the row before failing the job).

**Comment by katiecrane** [comment]
@DFurnes should we also _remove_ the [try/catch](https://github.com/DoSomething/chompy/blob/master/app/Jobs/CreateRockTheVotePostInRogue.php#L49-L55) when grabbing or creating users so that it will end up in the failed table?

**Comment by DFurnes** [comment]
Oh man, here's a potential culprit! Jen found this bad-boy on row 34 of this CSV: `‚™¥_ñ` 🙀

**Comment by DFurnes** [comment]
Oh, Jen found another one – this time a first name of `Ja_„ŽQuie`. I wonder if this is an issue with Redis not handling special UTF-8 characters correctly. We ran into something similar in Bertly I think...

**Comment by DFurnes** [comment]
And `D_„ŽJae`! Man, [who named these kids](https://xkcd.com/327/)!?

**Comment by chloealee** [comment]
@DFurnes since we are switching to SQS instead of Redis, do you think these special UTF-8 characters will be handled correctly now?
